# Generated by Django 5.0.2 on 2024-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('secondname', models.CharField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
    ]
